name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  project:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    
    steps:
    - name: Echo the message
      run:
        echo "Working"
    - name: Echo the message
      run:
        echo "Working"
=======
    steps:
    - name: Echo the message
      run:
        echo "Success"
>>>>>>> 0985c46ca33c79e5bb1eea338207bdfcf5089d8a
