name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the message
      run:
        echo "Success"
